// <auto-generated />
using System;
using IotManagerApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IotManagerApi.Migrations
{
    [DbContext(typeof(IotManagerDbContext))]
    partial class IotManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IotManagerApi.Database.BatchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BatchJob", (string)null);
                });

            modelBuilder.Entity("IotManagerApi.Database.BatchJob", b =>
                {
                    b.OwnsMany("IotManagerApi.Database.DeviceId", "DeviceIds", b1 =>
                        {
                            b1.Property<Guid>("BatchJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BatchJobId", "Id");

                            b1.ToTable("DeviceId");

                            b1.WithOwner()
                                .HasForeignKey("BatchJobId");
                        });

                    b.OwnsMany("IotManagerApi.Database.TagKey", "TagsToDelete", b1 =>
                        {
                            b1.Property<Guid>("BatchJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("BatchJobId", "Id");

                            b1.ToTable("TagKey");

                            b1.WithOwner()
                                .HasForeignKey("BatchJobId");
                        });

                    b.OwnsMany("IotManagerApi.Database.TagKeyValuePair", "TagsToSet", b1 =>
                        {
                            b1.Property<Guid>("BatchJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.HasKey("BatchJobId", "Id");

                            b1.ToTable("TagKeyValuePair");

                            b1.WithOwner()
                                .HasForeignKey("BatchJobId");
                        });

                    b.Navigation("DeviceIds");

                    b.Navigation("TagsToDelete");

                    b.Navigation("TagsToSet");
                });
#pragma warning restore 612, 618
        }
    }
}
